/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../listas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lists/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useListDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mylists` | `/mylists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/lists/ProductItem` | `/lists/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/lista/ProductItem` | `/lista/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/listas/[id]` | `/listas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../listas/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/lists/ProductItem`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useListDetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mylists` | `/mylists`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(list)'}/lists/ProductItem` | `/lists/ProductItem`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(list)'}/lista/ProductItem` | `/lista/ProductItem`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(list)'}/listas/[id]` | `/listas/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../listas/[id]${`?${string}` | `#${string}` | ''}` | `/../components/lists/ProductItem${`?${string}` | `#${string}` | ''}` | `/../hooks/useListDetails${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mylists${`?${string}` | `#${string}` | ''}` | `/mylists${`?${string}` | `#${string}` | ''}` | `${'/(list)'}/lists/ProductItem${`?${string}` | `#${string}` | ''}` | `/lists/ProductItem${`?${string}` | `#${string}` | ''}` | `${'/(list)'}/lista/ProductItem${`?${string}` | `#${string}` | ''}` | `/lista/ProductItem${`?${string}` | `#${string}` | ''}` | `${'/(list)'}/listas/[id]${`?${string}` | `#${string}` | ''}` | `/listas/[id]${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../listas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/../components/lists/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useListDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mylists` | `/mylists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/lists/ProductItem` | `/lists/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/lista/ProductItem` | `/lista/ProductItem`; params?: Router.UnknownInputParams; } | { pathname: `${'/(list)'}/listas/[id]` | `/listas/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
